# Generated by Django 5.0.14 on 2025-07-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineentry',
            name='mediciones_tecnicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='recibido_por_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='tipo_servicio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
