# Generated by Django 5.2.3 on 2025-07-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0002_machineentry_mediciones_tecnicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineentry',
            name='acepta_normativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='firma_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_clientes/'),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='tipo_consumidor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
