# Generated by Django 5.0.14 on 2025-07-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0003_machineentry_acepta_normativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineentry',
            name='fecha_autorizada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='fecha_cliente_inactivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='fecha_en_espera',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='fecha_en_reparacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='fecha_entregada_bodega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='fecha_entregada_cliente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='fecha_no_aceptada_cliente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='fecha_no_autorizada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='fecha_no_hay_repuestos',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='fecha_presupuestada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='fecha_reparada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='fecha_repuestos_recibidos',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='fecha_repuestos_solicitado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineentry',
            name='fecha_revision_taller',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machineentry',
            name='current_stage',
            field=models.CharField(choices=[('EN_ESPERA', 'EN ESPERA'), ('REVISION_TALLER', 'REVISION TALLER'), ('PRESUPUESTADA', 'PRESUPUESTADA'), ('AUTORIZADA', 'AUTORIZADA'), ('EN_REPARACION', 'EN REPARACION'), ('ENTREGADA_BODEGA', 'ENTREGADA BODEGA'), ('REPARADA', 'REPARADA'), ('ENTREGADA_CLIENTE', 'ENTREGADA CLIENTE'), ('NO_ACEPTADA_CLIENTE', 'NO ACEPTADA CLIENTE'), ('NO_AUTORIZADA', 'NO AUTORIZADA'), ('CLIENTE_INACTIVO', 'CLIENTE INACTIVO'), ('NO_HAY_REPUESTOS', 'NO HAY REPUESTOS'), ('REPUESTOS_SOLICITADO', 'REPUESTOS SOLICITADO'), ('REPUESTOS_RECIBIDOS', 'REPUESTOS RECIBIDOS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='repairhistory',
            name='stage',
            field=models.CharField(choices=[('EN_ESPERA', 'EN ESPERA'), ('REVISION_TALLER', 'REVISION TALLER'), ('PRESUPUESTADA', 'PRESUPUESTADA'), ('AUTORIZADA', 'AUTORIZADA'), ('EN_REPARACION', 'EN REPARACION'), ('ENTREGADA_BODEGA', 'ENTREGADA BODEGA'), ('REPARADA', 'REPARADA'), ('ENTREGADA_CLIENTE', 'ENTREGADA CLIENTE'), ('NO_ACEPTADA_CLIENTE', 'NO ACEPTADA CLIENTE'), ('NO_AUTORIZADA', 'NO AUTORIZADA'), ('CLIENTE_INACTIVO', 'CLIENTE INACTIVO'), ('NO_HAY_REPUESTOS', 'NO HAY REPUESTOS'), ('REPUESTOS_SOLICITADO', 'REPUESTOS SOLICITADO'), ('REPUESTOS_RECIBIDOS', 'REPUESTOS RECIBIDOS')], max_length=20),
        ),
    ]
